[server]
headless = true
port = 8501
enableCORS = false

[theme]
base = "light"
primaryColor = "#4f8bf9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333f"
font = "sans serif"