[theme]
primaryColor = "#6eb52f"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e6f7ff"
textColor = "#262730"
font = "sans serif"

[runner]
fastReruns = true

[server]
headless = true
enableCORS = false
port = 8501
